### PR TITLE
marker color and offcanvas

### PR DESCRIPTION
**Pull request by ds6332**
Marker color resets when detail panel is closed.

clicking marker when detail panel is open closes the panel.

show review even when user is logged out

### CODE REVIEW

**Review by TheHarbinger99 — APPROVED** [review]
lgtm

**Review by TheHarbinger99 — APPROVED** [review]
lgtm

**Review by AdnanAhsanNYCity — APPROVED** [review]
lgtm

**Review by as14680 — APPROVED** [review]
lgtm, do show the changes in tomorrow's scrum

**Pull request merged**
