### PR TITLE
Forgot password

### PR DESCRIPTION
**Pull request by guptaviha**
This PR includes the following:

1. Forgot password flow. Enter email -> get code in email -> enter code + new password -> login with new password
2. Includes miltilogin code from Suyash
3. One time like/dislike for review (temp fix)
4. Highlighting selected amenity by changing color
5. Fixed settings drop down empty bug by removing it when empty
6. Added template About page
7. Logo

Collaborators: Suyash and Viha

### CODE REVIEW

**Review by ds6332 — APPROVED** [review]
looks good. too big a PR though for review.

**Review by TheHarbinger99 — APPROVED** [review]
lgtm

**Comment by guptaviha** [comment]
> looks good. too big a PR though for review.

Yeah its a big one. But if you can check if the features work as expected on your machine, that would be helpful

**Comment by guptaviha** [comment]
Build was all good. Coverage was down 0.5%. Thats why it says 1 check failed

**Pull request merged**
