### PR TITLE
like,dislike button disable timer

### PR DESCRIPTION
**Pull request by ds6332**
Like, dislike buttons disabled for 5 seconds after click

### CODE REVIEW

**Review by TheHarbinger99 — APPROVED** [review]
lgtm

**Review by as14680 — CHANGES_REQUESTED** [review]
Noticed a Bug on local, don't push this PR for now until the bug is resolved.

**Comment by ds6332** [comment]
> Noticed a Bug on local, don't push this PR for now until the bug is resolved.

i couldn't reproduce on staging.. Even if it's a bug, it's completely unrelated to the PR

**Review by guptaviha — APPROVED** [review]
Logic looks good. Havent run it on local but giving my approval nonetheless

**Review by AdnanAhsanNYCity — APPROVED** [review]
Went over and couldn't replicate the bug, seems good on my end

**Pull request merged**
