### PR TITLE
Be login viha

### PR DESCRIPTION
**Pull request by guptaviha**
includes fe and be of login and signup

### CODE REVIEW

**Review by TheHarbinger99 — COMMENTED** [review]
lgtm

**Review by TheHarbinger99 — DISMISSED** [review]
lgtm

**Review by AdnanAhsanNYCity — APPROVED** [review]
Seems good!

**Review by ds6332 — APPROVED** [review]
looks good

**Review by TheHarbinger99 — APPROVED** [review]
lgtm

**Review by AdnanAhsanNYCity — APPROVED** [review]
Lgtm

**Review by as14680 — APPROVED** [review]
For login and registration. The code is good!

**Pull request merged**
