### PR TITLE
FE Tests for old code

### PR DESCRIPTION
**Pull request by guptaviha**
Hi team, I added 6 new tests to check for: 
1. the appearance of the user location marker on the page load (1 test)
2. the appearance/ disappearance of amenity markers on the toggle of filter buttons. (5 tests)

### CODE REVIEW

**Review by as14680 — DISMISSED** [review]
Do check the coverage value in the coverall dashboard. https://coveralls.io/github/gcivil-nyu-org/team-5-inperson

**Review by AdnanAhsanNYCity — APPROVED** [review]
Looks good to me.

**Review by AdnanAhsanNYCity — APPROVED** [review]
lgtm

**Review by as14680 — APPROVED** [review]
Looks good to me

**Pull request merged**
